sudo: false
language: python
python:
  - "3.5"
branches:
  only:
    - master

install:
  - python setup.py install
  - pip install git+https://github.com/behdad/fonttools
  - pip install git+https://github.com/unified-font-object/ufoLib

script:
  - python setup.py test
